### ISSUE TITLE
Top Center Arrow Issue

### ISSUE THREAD

**Issue by DimitarGR8** [SmartToolFactory/Compose-Speech-Bubble#1]
Hey, have you tested to show the arrow with the TopCenter alignment? I think there is an issue with it.

**Comment by SmartToolFactory** [comment]
I tested it but, of course, there can be an issue. What's the issue you experienced? Any snippet or image would be helpful to understand it.

**Comment by DimitarGR8** [comment]
Yes, of course. This code snippet, basically does not draw the arrow on top of the bubble. It actually leaves space for it, however, it does not draw it. Or I am missing something?

val bubbleStateBottom1 = rememberBubbleState(
      backgroundColor = Color(0xfffbc02d),
      alignment = ArrowAlignment.TopCenter,
      arrowShape = ArrowShape.TRIANGLE_ISOSCELES,
      cornerRadius = 8.dp,
      shadow = BubbleShadow(
          elevation = 1.dp
      ),
      padding = Padding(8.dp)
  )

  BubbleLayout(
      modifier = Modifier.horizontalAlign(HorizontalAlignment.Center),
      bubbleState = bubbleStateBottom1
  ) {
      Text(text = "Arrow should be top center, but it is missing..", color = Color.White)
  }
}

![image](https://user-images.githubusercontent.com/53057610/193288524-ce49eb99-cf10-4573-b370-d123bf0b574d.png)

**Comment by SmartToolFactory** [comment]
Thanks for the feedback. I will check this and update if there are any bugs.

**Comment by DimitarGR8** [comment]
In case of no issues, could you please let me know what am I missing? Thanks in advance!

**Comment by SmartToolFactory** [comment]
There are many issues with BubbleColumn. Since i haven't created any release yet for this library i will remove it, instead of deprecating, and create a release  only with Modifier.drawBubble, Modifier.drawBubbleShape, and option to get bubble shape which you can easily add padding as big as arrow width or height to not place Composables where arrow is
