### ISSUE TITLE
Lib version

### ISSUE THREAD

**Issue by BrianMwas** [SmartToolFactory/Compose-Speech-Bubble#2]
Hey amazing work, just wanted to know how I can add it in to my project with grade can't seem to find the version number

**Comment by SmartToolFactory** [comment]
For now you can copy paste lib code into your project. I will rewrite this code with better approach, only with Modifier.layout and creating a GenericShape. I posted simpler version of new code in [Compose Tutorial](https://github.com/SmartToolFactory/Jetpack-Compose-Tutorials/blob/master/Tutorial1-1Basics/src/main/java/com/smarttoolfactory/tutorial1_1basics/chapter3_layout/Tutorial3_2_7ConstraintsAndLayout.kt)

**Comment by BrianMwas** [comment]
Thanks that's what I did
